import { randomUUID } from 'node:crypto';
import { link, mkdir, open, readdir, readFile, stat, unlink, utimes } from 'node:fs/promises';
import { basename, join } from 'node:path';

type Phase = 'choosing' | 'ticket';
interface Owner { pid: number; token: string; createdAt: string; phase: Phase; ticketNumber?: number; }
interface RecordEntry { owner: Owner; path: string; raw: string; phase: Phase; }
type Stage = 'after-temp-open' | 'before-ticket-publish' | 'before-final-scan' | 'after-temp-fsync' | 'after-link' | 'before-stale-unlink';
export interface SourceLockOptions { root: string; retryMs?: number; timeoutMs?: number; staleAfterMs?: number; }
interface SourceLockDependencies { now?: () => number; pid?: number; isProcessAlive?: (pid: number) => boolean; tokenFactory?: () => string; hook?: (stage: Stage, owner: Owner) => Promise<void> | void; read?: typeof readFile; readdir?: typeof readdir; link?: typeof link; directorySync?: (directory: string) => Promise<void>; }
const TOKEN = /^[A-Za-z0-9_-]{1,64}$/u; const MAX_TICKET = 1_000_000_000;
const sourceLeaseBrand = Symbol('agentwiki-source-lock-lease');
export type SourceLockLease = Readonly<{
  sourceKey: string;
  token: string;
  [sourceLeaseBrand]: true;
}>;
const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));
const missing = (error: unknown) => typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT';
const validDate = (value: unknown): value is string => typeof value === 'string' && Number.isFinite(Date.parse(value));

/** A disk-backed Lamport bakery lock, scoped to one CodeGraph source key. */
export class SourceLock {
  private readonly retry: number; private readonly timeout: number; private readonly staleAfter: number; private readonly now: () => number; private readonly alive: (pid: number) => boolean; private readonly token: () => string;
  /** Runtime identity prevents casts, copied objects, and another lock instance from forging a lease. */
  private readonly activeLeases = new WeakMap<SourceLockLease, { sourceKey: string; token: string }>();
  constructor(private readonly options: SourceLockOptions, /** @internal */ private readonly dependencies: SourceLockDependencies = {}) { this.retry = options.retryMs ?? 20; this.timeout = options.timeoutMs ?? 30_000; this.staleAfter = options.staleAfterMs ?? 300_000; this.now = dependencies.now ?? Date.now; this.alive = dependencies.isProcessAlive ?? ((pid) => { try { process.kill(pid, 0); return pid > 0; } catch (error: unknown) { return typeof error === 'object' && error !== null && 'code' in error && error.code === 'EPERM'; } }); this.token = dependencies.tokenFactory ?? randomUUID; }
  private dir(key: string) { if (!/^[a-f0-9]{64}$/u.test(key)) throw new Error('Invalid source key for local scan lock'); return join(this.options.root, `.codegraph-${key}.coordination`); }
  private legacyBase(key: string) { return join(this.options.root, `.codegraph-${key}.lock`); }
  private file(dir: string, phase: Phase, pid: number, token: string) { return join(dir, `${phase}-${pid}-${token}.json`); }
  private parse(name: string, pattern: RegExp): { phase: Phase; pid: number; token: string } | null { const match = pattern.exec(name); if (!match) return null; const pid = Number(match[2]); return Number.isSafeInteger(pid) ? { phase: match[1] as Phase, pid, token: match[3] } : null; }
  private parseVisible(name: string) { return this.parse(name, /^(choosing|ticket)-([1-9][0-9]*)-([A-Za-z0-9_-]{1,64})\.json$/u); }
  private parsePrivate(name: string) { return this.parse(name, /^\.private-(choosing|ticket)-([1-9][0-9]*)-([A-Za-z0-9_-]{1,64})~[A-Za-z0-9-]+$/u); }
  private parseStaging(name: string) { return this.parse(name, /^\.staging-(choosing|ticket)-([1-9][0-9]*)-([A-Za-z0-9_-]{1,64})~[A-Za-z0-9-]+$/u); }
  private valid(data: unknown, phase: Phase, pid: number, token: string): data is Owner { if (!data || typeof data !== 'object' || Array.isArray(data)) return false; const value = data as Record<string, unknown>; const wanted = phase === 'ticket' ? ['createdAt', 'phase', 'pid', 'ticketNumber', 'token'] : ['createdAt', 'phase', 'pid', 'token']; const keys = Object.keys(value).sort(); return keys.length === wanted.length && keys.every((key, index) => key === wanted[index]) && value.pid === pid && Number.isSafeInteger(value.pid) && pid > 0 && value.token === token && TOKEN.test(token) && value.phase === phase && validDate(value.createdAt) && (phase === 'choosing' || (Number.isSafeInteger(value.ticketNumber) && (value.ticketNumber as number) > 0 && (value.ticketNumber as number) <= MAX_TICKET)); }
  private async stale(path: string, pid: number, createdAt?: string) { try { const metadata = await stat(path); const age = this.now() - Math.max(metadata.mtimeMs, createdAt ? Date.parse(createdAt) : Number.NEGATIVE_INFINITY); return Number.isFinite(age) && age >= this.staleAfter && !this.alive(pid); } catch (error) { if (missing(error)) return false; throw new Error('Unable to inspect local scan lock record', { cause: error }); } }
  private async raw(path: string): Promise<string | null> { try { return await (this.dependencies.read ?? readFile)(path, 'utf8'); } catch (error) { if (missing(error)) return null; throw new Error('Unable to read local scan lock record', { cause: error }); } }
  private async names(path: string): Promise<string[]> { try { return await (this.dependencies.readdir ?? readdir)(path); } catch (error) { if (missing(error)) return []; throw new Error('Unable to inspect local scan lock records', { cause: error }); } }
  private async syncDirectory(directory: string) { if (this.dependencies.directorySync) return this.dependencies.directorySync(directory); const handle = await open(directory, 'r'); try { await handle.sync(); } finally { await handle.close(); } }
  /** Recheck bytes immediately before unlinking so a later owner is never removed by a stale observer. */
  private async removeUnchanged(path: string, expected: string, owner?: Owner): Promise<boolean> { const current = await this.raw(path); if (current === null || current !== expected) return false; if (owner) await this.dependencies.hook?.('before-stale-unlink', owner); const beforeUnlink = await this.raw(path); if (beforeUnlink === null || beforeUnlink !== expected) return false; try { await unlink(path); return true; } catch (error) { if (missing(error)) return false; throw error; } }
  private async malformedPrivate(path: string, raw: string, parsed: { phase: Phase; pid: number; token: string }, data: unknown): Promise<RecordEntry | null> { if (data && typeof data === 'object' && !Array.isArray(data)) { const value = data as Record<string, unknown>; if (('pid' in value && (typeof value.pid !== 'number' || value.pid !== parsed.pid)) || ('token' in value && (typeof value.token !== 'string' || value.token !== parsed.token)) || ('phase' in value && value.phase !== parsed.phase)) throw new Error('Malformed local scan lock record'); } if (await this.stale(path, parsed.pid)) { await this.removeUnchanged(path, raw); return null; } throw new Error('Malformed local scan lock record'); }
  private async entry(dir: string, name: string, privateRecord: boolean): Promise<RecordEntry | null> { const parsed = privateRecord ? this.parsePrivate(name) : this.parseVisible(name); if (!parsed) return null; const path = join(dir, name); const raw = await this.raw(path); if (raw === null) return null; let data: unknown; try { data = JSON.parse(raw); } catch { if (privateRecord) return this.malformedPrivate(path, raw, parsed, undefined); if (await this.stale(path, parsed.pid)) { await this.removeUnchanged(path, raw); return null; } throw new Error('Malformed local scan lock record'); } if (!this.valid(data, parsed.phase, parsed.pid, parsed.token)) { if (privateRecord) return this.malformedPrivate(path, raw, parsed, data); if (await this.stale(path, parsed.pid)) { await this.removeUnchanged(path, raw); return null; } throw new Error('Malformed local scan lock record'); } const owner = data; if (await this.stale(path, owner.pid, owner.createdAt)) { await this.removeUnchanged(path, raw, owner); return null; } return { owner, path, raw, phase: parsed.phase }; }
  private async list(dir: string, privateRecord: boolean) { const names = await this.names(dir); const records: RecordEntry[] = []; for (const name of names) { if (privateRecord !== name.startsWith('.private-')) continue; const record = await this.entry(dir, name, privateRecord); if (record) records.push(record); } return records; }
  private async cleanupPrivate(dir: string) { for (const name of await this.names(dir)) if (name.startsWith('.private-')) await this.entry(dir, name, true); }
  private async cleanupStaging(dir: string) { for (const name of await this.names(dir)) { const parsed = this.parseStaging(name); if (!parsed) continue; const path = join(dir, name); const raw = await this.raw(path); if (raw === null) continue; let data: unknown; try { data = JSON.parse(raw); } catch { continue; } if (!this.valid(data, parsed.phase, parsed.pid, parsed.token)) continue; if (await this.stale(path, parsed.pid, data.createdAt)) await this.removeUnchanged(path, raw, data); } }
  private async cleanupLegacyResidues(key: string) { const base = this.legacyBase(key); const escaped = basename(base).replace(/[.*+?^${}()|[\]\\]/gu, '\\$&'); const pattern = new RegExp(`^${escaped}\\.(?:candidate-([A-Za-z0-9_-]{1,64})|quarantine-([A-Za-z0-9_-]{1,64})-[A-Za-z0-9-]+)$`, 'u'); for (const name of await this.names(this.options.root)) { const match = pattern.exec(name); if (!match) continue; const token = match[1] ?? match[2]; const path = join(this.options.root, name); const raw = await this.raw(path); if (raw === null) continue; let data: unknown; try { data = JSON.parse(raw); } catch { continue; } if (!data || typeof data !== 'object' || Array.isArray(data)) continue; const owner = data as Record<string, unknown>; if (!Number.isSafeInteger(owner.pid) || (owner.pid as number) <= 0 || owner.token !== token || !TOKEN.test(token) || !validDate(owner.createdAt)) continue; if (await this.stale(path, owner.pid as number, owner.createdAt)) await this.removeUnchanged(path, raw); } }
  private async removePublished(path: string, raw: string, directory: string) { try { if (await readFile(path, 'utf8') === raw) { await unlink(path); await this.syncDirectory(directory); } } catch { /* Preserve the publication failure; cleanup is best effort. */ } }
  private async publish(dir: string, owner: Owner): Promise<RecordEntry> { const raw = JSON.stringify(owner); const visible = this.file(dir, owner.phase, owner.pid, owner.token); const suffix = randomUUID(); const staging = join(dir, `.staging-${owner.phase}-${owner.pid}-${owner.token}~${suffix}`); const guard = join(dir, `.private-${owner.phase}-${owner.pid}-${owner.token}~${suffix}`); let guardLinked = false; let visibleLinked = false; try { const handle = await open(staging, 'wx', 0o600); try { await this.dependencies.hook?.('after-temp-open', owner); await handle.writeFile(raw, 'utf8'); await handle.sync(); } finally { await handle.close(); } try { await (this.dependencies.link ?? link)(staging, guard); guardLinked = true; } catch (error) { if (typeof error === 'object' && error !== null && 'code' in error && error.code === 'EEXIST') throw new Error('Local scan lock token collision', { cause: error }); throw error; } await this.syncDirectory(dir); await this.dependencies.hook?.('after-temp-fsync', owner); try { await (this.dependencies.link ?? link)(guard, visible); visibleLinked = true; } catch (error) { if (typeof error === 'object' && error !== null && 'code' in error && error.code === 'EEXIST') throw new Error('Local scan lock token collision', { cause: error }); throw error; } await this.syncDirectory(dir); await unlink(guard); guardLinked = false; await this.syncDirectory(dir); await this.dependencies.hook?.('after-link', owner); return { owner, path: visible, raw, phase: owner.phase }; } catch (error) { if (visibleLinked) await this.removePublished(visible, raw, dir); if (guardLinked) await this.removePublished(guard, raw, dir); throw error; } finally { await unlink(staging).catch(() => undefined); } }
  private same(left: Owner, right: Owner) { return left.pid === right.pid && left.token === right.token; }
  private assertNoForeignSameToken(records: RecordEntry[], owner: Owner) { if (records.some((record) => record.owner.token === owner.token && !this.same(record.owner, owner))) throw new Error('Local scan lock identity conflict'); }
  private compareTickets(left: RecordEntry, right: RecordEntry) { const ticket = left.owner.ticketNumber! - right.owner.ticketNumber!; if (ticket !== 0) return ticket; if (left.owner.token < right.owner.token) return -1; if (left.owner.token > right.owner.token) return 1; return left.owner.pid - right.owner.pid; }
  private async removeOwn(record: RecordEntry | undefined) { if (!record) return; try { if (await readFile(record.path, 'utf8') === record.raw) await unlink(record.path); } catch (error) { if (!missing(error)) throw error; } }
  private async acquire(key: string): Promise<RecordEntry> { const dir = this.dir(key); await mkdir(dir, { recursive: true, mode: 0o700 }); await this.cleanupStaging(dir); await this.cleanupPrivate(dir); await this.cleanupLegacyResidues(key); const token = this.token(); if (!TOKEN.test(token)) throw new Error('Invalid local scan lock token'); const pid = this.dependencies.pid ?? process.pid; if (!Number.isSafeInteger(pid) || pid <= 0) throw new Error('Invalid local scan lock pid'); const choosing: Owner = { pid, token, createdAt: new Date(this.now()).toISOString(), phase: 'choosing' }; const deadline = this.now() + this.timeout; let choosingRecord: RecordEntry | undefined; let ticketRecord: RecordEntry | undefined; try { choosingRecord = await this.publish(dir, choosing); const before = await this.list(dir, false); const guardsBefore = await this.list(dir, true); this.assertNoForeignSameToken([...before, ...guardsBefore], choosing); const maximum = Math.max(0, ...before.filter((record) => record.phase === 'ticket').map((record) => record.owner.ticketNumber!)); if (maximum >= MAX_TICKET) throw new Error('Local scan lock ticket overflow'); const ticket: Owner = { ...choosing, phase: 'ticket', ticketNumber: maximum + 1 }; await this.dependencies.hook?.('before-ticket-publish', ticket); ticketRecord = await this.publish(dir, ticket); await this.removeOwn(choosingRecord); choosingRecord = undefined; while (true) { await this.dependencies.hook?.('before-final-scan', ticket); const records = await this.list(dir, false); const guards = await this.list(dir, true); this.assertNoForeignSameToken([...records, ...guards], ticket); const choosingOther = records.some((record) => record.phase === 'choosing' && !this.same(record.owner, ticket)) || guards.some((record) => !this.same(record.owner, ticket)); const tickets = records.filter((record) => record.phase === 'ticket').sort((left, right) => this.compareTickets(left, right)); if (!choosingOther && tickets[0] && this.same(tickets[0].owner, ticket)) return ticketRecord; if (this.now() >= deadline) throw new Error('Timed out waiting for the local scan source lock'); await sleep(this.retry); } } catch (error) { await this.removeOwn(choosingRecord); await this.removeOwn(ticketRecord); throw error; } }
  assertLease(key: string, lease: SourceLockLease): void {
    const active = lease && typeof lease === 'object' ? this.activeLeases.get(lease) : undefined;
    if (!active || active.sourceKey !== key || active.token !== lease.token || lease.sourceKey !== key) {
      throw new Error('Invalid or inactive local scan source lease');
    }
  }
  async withLock<T>(key: string, work: (lease: SourceLockLease) => Promise<T>): Promise<T> {
    const ticket = await this.acquire(key);
    const lease = Object.freeze({ sourceKey: key, token: ticket.owner.token, [sourceLeaseBrand]: true }) as SourceLockLease;
    this.activeLeases.set(lease, { sourceKey: key, token: ticket.owner.token });
    try { return await work(lease); } finally { this.activeLeases.delete(lease); await this.removeOwn(ticket); }
  }
  async waitForTicketForTest(key: string) { const dir = this.dir(key); for (let attempt = 0; attempt < 100; attempt += 1) { if ((await this.list(dir, false)).some((record) => record.phase === 'ticket')) return; await sleep(1); } throw new Error('ticket not published'); }
  async createStaleForTest(key: string, token: string, phase: Phase, aged = true) { const dir = this.dir(key); await mkdir(dir, { recursive: true }); const owner: Owner = { pid: 999999, token, createdAt: new Date(this.now() - (aged ? 10_000 : 0)).toISOString(), phase, ...(phase === 'ticket' ? { ticketNumber: 1 } : {}) }; const record = await this.publish(dir, owner); if (aged) { const date = new Date(this.now() - 10_000); await utimes(record.path, date, date); } }
  async entriesForTest(key: string) { return (await this.list(this.dir(key), false)).map((record) => record.path); }
}
